### PR TITLE
H8A4 Indes Boundaries

### PR DESCRIPTION
**Pull request by jlmuldoon**

### CODE REVIEW

**Comment by MicheleTobias** [comment]
Thank you for sending this data!  I'm going to go ahead and merge your pull request because I want to ensure we have the data, but you need to do some data clean up.  
File names need to be standardized:
 * file names should be the call number for the air photo set you digitized
 * remove punctuation like "." 
 * (2) need to be removed
 * file names should not have spaces.  Use _ instead

Also, be sure all the attribute tables are filled out as best you can.  I haven't checked them yet, but I want you to take responsibility for that.

When you've made the changes, send a new pull request.

**Comment by jlmuldoon** [comment]
Hi Michele,

Did you say in the second bullet point that we cannot use periods, as in
"." and not quotation marks? Just want to make sure.

Thank you,
Jake

**Comment by MicheleTobias** [comment]
Don't use periods or quotation marks.

**Comment by MicheleTobias** [comment]
The only period you can use is before the file name so filename.geojson is good but file.name.geojson is bad.

**Pull request merged**
